resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
replicaCount: 1
image:
  repository: birendramondal/daemon_monitor
  tag: frontend_v1.0
  pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 80
api:
  baseUrl: "http://127.0.0.1:5000"
